version: "3.7"

services:
version: "3.7"

services: 
  # nginx:
  #   restart: always
  #   build:
  #     context: ./nginx
  #   ports:
  #     - 5678:80
  web-server:
    volumes: 
      - /web-server:/web-server/
    build:
      context: ./server # where to look for Dockerfile
      dockerfile: Dockerfile.dev # what dockerfile
    environment:
      PORT: 5000
    ports:
      - 5000:5000

  web-app:
    stdin_open: true # needed to allow react-scripts to watch for changes
    build:
      context: ./web-app # where to look for Dockerfile
      dockerfile: Dockerfile.dev # what dockerfile
    volumes:
      - ./web-app:/web-app/
    ports:
      - 4000:4000 # map the localhost 4000 -> 4000
    environment:
      PORT: 4000 # set port of react app inside docker container to 4000 instead of 3000 (default)
      REACT_APP_APOLLO_URI: http://localhost:5000/graphql
    