version: "3.7"

networks:
  frontend: # nginx <--> web-app
  backend: # nginx <--> web-server

services:
  web-server:
    volumes:
      - ./web-server:/web-server/ #first web-server is path to src app --- second web-server is folder where all all files save
    build:
      context: ./web-server # where to look for Dockerfile
      dockerfile: Dockerfile.dev # what dockerfile
    environment:
      PORT: 5000
      MONGO_URI: mongodb+srv://biem97:8uf3aBFLyW3YNzb4@papertrading.8wat4.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
    # ports:
    #   - 5000:5000      # DON'T map the container port to user localhost, let nginx do it
    networks:
      - backend

  web-app:
    stdin_open: true # needed to allow react-scripts to watch for changes
    build:
      context: ./web-app # where to look for Dockerfile
      dockerfile: Dockerfile.dev # what dockerfile
    volumes:
      - ./web-app:/web-app/ #first web-app is path to src app --- second web-app is folder where all all files save
    environment:
      PORT: 4000 # set port of react app inside docker container to 4000 instead of 3000 (default)
    # ports:
    #   - 4000:4000 # map the localhost 4000 -> 4000 # DON'T map the container port to user localhost, let nginx do it
    networks:
      - frontend

  nginx:
    restart: always
    build:
      context: ./nginx # where to look for Dockerfile
      dockerfile: Dockerfile # what dockerfile
    ports:
      - 1997:997 # ONLY nginx map the host to  user localhost
    networks:
      - frontend
      - backend
    depends_on:
      - web-app
      - web-server
