version: "3.7"

networks:
  frontend: # nginx <--> web_app
  backend: # nginx <--> web-server

services:
  web-server:
    volumes:
      - /web-server:/web-server/ #first web-server is name of container --- second web-server is folder where all all files save
    build:
      context: ./server # where to look for Dockerfile
      dockerfile: Dockerfile.dev # what dockerfile
    environment:
      PORT: 5000
    # ports:
    #   - 5000:5000      # DON'T map the container port to user localhost, let nginx do it
    networks:
      - backend

services: 
  web-app:
    container_name: web-app
    stdin_open: true # needed to allow react-scripts to watch for changes
    build:
      context: ./web-app # where to look
      dockerfile: Dockerfile.dev # what dockerfile
    volumes:
      - ./web-app:/app/
      - /app/node_modules
    ports:
      - 3123:4000 # map the localhost 3123 -> 4000
    environment:
      PORT: 4000 # set port of react app inside docker container to 4000 instead of 3000 (default)
    # ports:
    #   - 4000:4000 # map the localhost 4000 -> 4000 # DON'T map the container port to user localhost, let nginx do it
    networks:
      - frontend

  nginx:
    restart: always
    build:
      context: ./nginx # where to look for Dockerfile
      dockerfile: Dockerfile # what dockerfile
    ports:
      - 1997:997 # ONLY nginx map the host to  user localhost
    networks:
      - frontend
      - backend
    depends_on:
      - web-app
      - web-server
