version: "3.7"

services:
version: "3.7"

services: 
  web-app:
    container_name: web-app
    stdin_open: true # needed to allow react-scripts to watch for changes
    build:
      context: ./web-app # where to look
      dockerfile: Dockerfile.dev # what dockerfile
    volumes:
      - ./web-app:/app/
      - /app/node_modules
    ports:
      - 3123:4000 # map the localhost 3123 -> 4000
    environment:
      PORT: 4000 # set port of react app inside docker container to 4000
      REACT_APP_APOLLO_URI: http://localhost:5000/graphql
    links:
      - server
  server:
    container_name: server
    build:
      context: ./server # where to look
      dockerfile: Dockerfile.dev # what dockerfile
    environment:
      PORT: 5000
    ports:
      - 5000:5000
